import React, { useState } from 'react';

const faqData = [
  {
      question: "What is a SUB BROKER?",
      answer: "A Sub-Broker or Authorized Person acts as an extension of a primary stockbroker like DB Fintrix. You can acquire clients and facilitate their trading, while we provide the trading platform, research, and back-office support. You earn a highly lucrative percentage of the brokerage generated by your clients."
  },
  {
      question: "Investment required?",
      answer: "Partnering with DB Fintrix requires minimal initial capital. You only need basic office infrastructure and a one-time refundable security deposit as mandated by regulatory authorities."
  },
  {
      question: "Eligibility?",
      answer: "Anyone with a strong network and basic understanding of financial markets can become a partner. You must be at least 21 years old, have completed your HSC (12th grade), and hold relevant NISM certifications."
  },
  {
      question: "Documents needed?",
      answer: "You will need standard KYC documents: PAN Card, Aadhaar Card, Address Proof, Bank Proof (Cancelled Cheque), educational certificates, and your NISM passing certificates."
  },
  {
      question: "Revenue sharing?",
      answer: "We offer the most competitive and transparent revenue-sharing models in the industry, which can go up to 70%-80% depending on your volume and client base, ensuring maximum profitability for our partners."
  },
  {
      question: "Support provided?",
      answer: "We provide end-to-end support including a dedicated Relationship Manager, a fully loaded back-office dashboard for client tracking, marketing collateral, and complete compliance assistance."
  },
  {
      question: "Training?",
      answer: "Yes! We offer comprehensive onboarding and continuous training. This includes product training, software demos, and regular market outlook webinars to help you grow your business."
  },
  {
      question: "Time to start?",
      answer: "With our seamless digital onboarding process, your partnership code can be generated and activated within 3 to 5 working days after all documents are successfully verified."
  }
];

const Faq = () => {
  const [openIndex, setOpenIndex] = useState(null);

  const toggleFaq = (index) => {
    setOpenIndex(openIndex === index ? null : index);
  };

  return (
    <section className="bg-white py-20 md:py-24">
      <div className="container mx-auto px-6 max-w-4xl">
        
        {/* Header */}
        <div className="text-center mb-16">
          <h2 className="text-4xl md:text-5xl font-bold text-brand-dark tracking-tight mb-4 uppercase">
            Frequently Asked <span className="text-brand-green">Questions</span>
          </h2>
          <p className="text-gray-500 text-lg">
            Got questions? We have got answers. Here are some of the most common questions our users ask.
          </p>
        </div>

        {/* FAQ Accordion */}
        <div className="space-y-4">
          {faqData.map((faq, index) => {
            const isOpen = openIndex === index;
            return (
              <div 
                key={index} 
                className={`border rounded-2xl transition-all duration-300 ${
                  isOpen ? 'border-brand-green shadow-md bg-white' : 'border-gray-200 bg-gray-50 hover:border-gray-300'
                }`}
              >
                <button
                  className="w-full flex items-center justify-between p-6 text-left focus:outline-none"
                  onClick={() => toggleFaq(index)}
                >
                  <span className={`text-lg font-bold ${isOpen ? 'text-brand-green' : 'text-brand-dark'}`}>
                    {faq.question}
                  </span>
                  <span 
                    className={`flex items-center justify-center w-8 h-8 rounded-full text-xl transition-transform duration-300 ${
                      isOpen ? 'bg-brand-green text-white rotate-180' : 'bg-gray-200 text-gray-500'
                    }`}
                  >
                    {isOpen ? '−' : '+'}
                  </span>
                </button>
                
                <div 
                  className={`overflow-hidden transition-all duration-300 ease-in-out ${
                    isOpen ? 'max-h-96 opacity-100' : 'max-h-0 opacity-0'
                  }`}
                >
                  <p className="px-6 pb-6 text-gray-600 leading-relaxed">
                    {faq.answer}
                  </p>
                </div>
              </div>
            );
          })}
        </div>

      </div>
    </section>
  );
};

export default Faq;
