import React, { useState } from 'react';
import { ChevronRight, TrendingUp, PiggyBank, Shield, Award, Landmark, Wallet, Layers, Compass } from 'lucide-react';
import AnimatedWords from '../../Comman components/AnimatedWords';

const opportunities = [
    {
        title: "Brokerage Sharing",
        description: "Earn a highly competitive percentage of the brokerage generated by your clients' trading activities.",
        icon: <TrendingUp className="w-5 h-5" />,
        accent: "from-blue-500 to-indigo-600",
        borderActive: "border-blue-500 bg-blue-50/40 text-blue-600"
    },
    {
        title: "Mutual Fund Distribution",
        description: "Build a stable trail income by distributing a wide variety of direct and regular mutual funds.",
        icon: <PiggyBank className="w-5 h-5" />,
        accent: "from-emerald-500 to-green-600",
        borderActive: "border-emerald-500 bg-emerald-50/40 text-emerald-600"
    },
    {
        title: "Insurance",
        description: "Cross-sell life and general insurance products to your clients and earn attractive commissions.",
        icon: <Shield className="w-5 h-5" />,
        accent: "from-purple-500 to-pink-600",
        borderActive: "border-purple-500 bg-purple-50/40 text-purple-600"
    },
    {
        title: "IPOs",
        description: "Facilitate IPO investments for your network and get rewarded for successful allotments.",
        icon: <Award className="w-5 h-5" />,
        accent: "from-amber-500 to-yellow-600",
        borderActive: "border-amber-500 bg-amber-50/40 text-amber-600"
    },
    {
        title: "Loans & Margin Funding",
        description: "Refer clients for personal, business, or margin funding loans and earn lucrative referral fees.",
        icon: <Landmark className="w-5 h-5" />,
        accent: "from-teal-500 to-cyan-600",
        borderActive: "border-teal-500 bg-teal-50/40 text-teal-600"
    },
    {
        title: "Bonds & Corporate FDs",
        description: "Provide safe fixed-income investment options to clients and earn steady distribution payouts.",
        icon: <Wallet className="w-5 h-5" />,
        accent: "from-indigo-500 to-blue-600",
        borderActive: "border-indigo-500 bg-indigo-50/40 text-indigo-600"
    },
    {
        title: "PMS & AIF Referrals",
        description: "Target High Net-worth Individuals for Portfolio Management Services and earn premium commissions.",
        icon: <Layers className="w-5 h-5" />,
        accent: "from-rose-500 to-red-600",
        borderActive: "border-rose-500 bg-rose-50/40 text-rose-600"
    },
    {
        title: "Research Subscriptions",
        description: "Offer premium research and advisory subscriptions to your clients on a profit-sharing model.",
        icon: <Compass className="w-5 h-5" />,
        accent: "from-violet-500 to-purple-600",
        borderActive: "border-violet-500 bg-violet-50/40 text-violet-600"
    }
];

const IncomeOpportunity = () => {
    const [activeTab, setActiveTab] = useState(0);

    const currentOpportunity = opportunities[activeTab];

    return (
        <section className="bg-white py-20 md:py-28 relative overflow-hidden">
            <div className="container mx-auto px-6">
                <div className="flex flex-col lg:flex-row gap-16 lg:gap-20 items-start">
                    
                    {/* Left Side: Content & Interactive Cards */}
                    <div className="w-full lg:w-7/12 flex flex-col">
                        
                        {/* Header */}
                        <div className="mb-10">
                            <div className="inline-flex items-center gap-2 px-3.5 py-1 rounded-full bg-blue-50 text-brand-blue text-xs font-bold uppercase tracking-wider mb-4 border border-blue-100">
                                <span>High-Yield Partnership</span>
                            </div>

                            <h2 className="text-3xl sm:text-4xl md:text-5xl font-black text-[#1e2c4c] mb-4 tracking-tight leading-tight uppercase">
                                <AnimatedWords 
                                    text="MULTIPLE" 
                                    className="mr-3"
                                />
                                <span className="animate-text-gradient font-black block sm:inline">
                                    STREAMS OF INCOME
                                </span>
                            </h2>
                            <p className="text-gray-500 text-base md:text-lg leading-relaxed">
                                Partner with DB Fintrix and monetize your network across 8 different high-yielding financial products.
                            </p>
                        </div>

                        {/* Cards List */}
                        <div className="flex flex-col gap-3.5 pr-2">
                            {opportunities.map((item, index) => {
                                const isActive = activeTab === index;
                                return (
                                    <div 
                                        key={index}
                                        onMouseEnter={() => setActiveTab(index)}
                                        onClick={() => setActiveTab(index)}
                                        className={`group flex items-center justify-between p-5 md:p-5 rounded-2xl border transition-all duration-300 cursor-pointer ${
                                            isActive 
                                                ? `${item.borderActive} shadow-md translate-x-2` 
                                                : 'border-gray-200 hover:border-gray-300 bg-white hover:bg-gray-50/60'
                                        }`}
                                    >
                                        <div className="flex items-center gap-4 pr-4">
                                            <div className={`p-2.5 rounded-xl transition-colors ${
                                                isActive ? 'bg-white shadow-sm' : 'bg-gray-100 text-gray-400 group-hover:text-brand-dark'
                                            }`}>
                                                {item.icon}
                                            </div>
                                            <div>
                                                <h3 className={`font-bold text-base sm:text-lg mb-1 transition-colors ${
                                                    isActive ? 'text-[#1e2c4c]' : 'text-gray-800 group-hover:text-brand-dark'
                                                }`}>
                                                    {item.title}
                                                </h3>
                                                <p className="text-gray-500 text-xs sm:text-sm leading-relaxed">
                                                    {item.description}
                                                </p>
                                            </div>
                                        </div>
                                        <div className={`shrink-0 transition-transform ${
                                            isActive ? 'translate-x-1' : 'text-gray-300 group-hover:text-gray-400 group-hover:translate-x-1'
                                        }`}>
                                            <ChevronRight className="w-5 h-5" strokeWidth={2.5} />
                                        </div>
                                    </div>
                                );
                            })}
                        </div>
                    </div>

                    {/* Right Side: Animated Financial Graphic */}
                    <div className="w-full lg:w-5/12 relative hidden lg:flex items-center justify-center sticky top-28 h-[600px] transform scale-95 xl:scale-100 origin-right">
                        
                        {/* Decorative background ambient glow */}
                        <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[480px] h-[480px] rounded-full bg-gradient-to-tr from-blue-100/60 via-green-100/40 to-yellow-100/50 blur-2xl -z-10 animate-float-slow"></div>
                        
                        {/* Floating elements with soft pulses */}
                        <div className="absolute top-12 left-10 text-yellow-400 animate-pulse">
                            <svg width="28" height="28" viewBox="0 0 24 24" fill="currentColor"><path d="M12 2L15 9L22 12L15 15L12 22L9 15L2 12L9 9L12 2Z"/></svg>
                        </div>
                        <div className="absolute bottom-28 left-4 text-blue-400 animate-pulse delay-700">
                            <svg width="36" height="36" viewBox="0 0 24 24" fill="currentColor"><path d="M12 2L15 9L22 12L15 15L12 22L9 15L2 12L9 9L12 2Z"/></svg>
                        </div>

                        {/* Floating Icons Column */}
                        <div className="absolute -left-3 top-1/2 -translate-y-1/2 flex flex-col gap-3 bg-gradient-to-b from-blue-600 to-indigo-700 rounded-full p-2 py-5 shadow-2xl z-20 animate-float-delayed">
                            <div className="w-10 h-10 bg-white rounded-xl shadow-md flex items-center justify-center text-green-600 font-extrabold text-sm">₹</div>
                            <div className="w-10 h-10 bg-white rounded-xl shadow-md flex items-center justify-center text-blue-600 font-bold text-sm">📈</div>
                            <div className="w-10 h-10 bg-white rounded-xl shadow-md flex items-center justify-center text-amber-500 font-bold text-sm">★</div>
                        </div>

                        {/* Main Browser Window with Live Animated Chart */}
                        <div className="relative w-[480px] h-[360px] bg-white rounded-3xl shadow-[0_25px_60px_rgba(0,0,0,0.12)] border border-gray-100 flex flex-col z-10 overflow-hidden transform transition-all duration-500 hover:scale-105">
                            
                            {/* Browser Top Bar */}
                            <div className="h-12 bg-gradient-to-r from-[#1e2c4c] to-[#004aad] w-full flex items-center justify-between px-5">
                                <div className="flex gap-2">
                                    <div className="w-3 h-3 rounded-full bg-red-400"></div>
                                    <div className="w-3 h-3 rounded-full bg-yellow-400"></div>
                                    <div className="w-3 h-3 rounded-full bg-green-400"></div>
                                </div>
                                <div className="text-white/80 text-xs font-semibold tracking-wide">
                                    DB Fintrix Revenue Dashboard
                                </div>
                                <div className="w-4"></div>
                            </div>

                            {/* Browser Body with Live Animated Bars */}
                            <div className="p-6 bg-[#f8f9fe] flex-grow flex flex-col justify-between">
                                
                                <div className="flex gap-5 items-center">
                                    {/* Animated Bar Chart Box */}
                                    <div className="bg-white rounded-2xl p-4 flex-grow h-36 relative shadow-sm border border-gray-100">
                                        <div className="text-xs font-bold text-gray-500 mb-2 flex justify-between items-center">
                                            <span>Monthly Distribution Growth</span>
                                            <span className="text-green-600 font-extrabold">+34.8%</span>
                                        </div>
                                        <div className="absolute bottom-5 left-4 right-4 h-20 flex items-end justify-around gap-3">
                                            <div className="w-8 bg-gradient-to-t from-blue-500 to-cyan-400 rounded-t-lg bar-anim-1"></div>
                                            <div className="w-8 bg-gradient-to-t from-emerald-500 to-green-400 rounded-t-lg bar-anim-2"></div>
                                            <div className="w-8 bg-gradient-to-t from-amber-500 to-yellow-400 rounded-t-lg bar-anim-3"></div>
                                            <div className="w-8 bg-gradient-to-t from-purple-500 to-pink-400 rounded-t-lg bar-anim-4"></div>
                                        </div>
                                    </div>

                                    {/* Pie Chart / Speedometer Area */}
                                    <div className="flex flex-col gap-3 items-center justify-center p-3 bg-white rounded-2xl border border-gray-100 shadow-sm w-28">
                                        <div className="w-16 h-16 rounded-full bg-gradient-to-tr from-brand-green to-emerald-300 p-1 shadow-inner flex items-center justify-center animate-spin-slow">
                                            <div className="w-full h-full bg-white rounded-full flex items-center justify-center text-xs font-black text-brand-dark">
                                                80%
                                            </div>
                                        </div>
                                        <span className="text-[10px] font-extrabold text-gray-500 uppercase text-center">
                                            Payout Ratio
                                        </span>
                                    </div>
                                </div>

                                {/* Active Highlight Information */}
                                <div className="p-3 bg-blue-50/80 rounded-xl border border-blue-100 flex items-center justify-between">
                                    <span className="text-xs font-bold text-brand-dark">
                                        Current Channel: <span className="text-brand-blue">{currentOpportunity.title}</span>
                                    </span>
                                    <span className="text-xs font-extrabold text-brand-green">Active Stream</span>
                                </div>

                            </div>
                        </div>

                        {/* Floating Coins with 3D Bobbing */}
                        <div className="absolute -bottom-5 right-8 flex z-30 drop-shadow-xl animate-coin-bob">
                            <div className="w-16 h-16 rounded-full bg-gradient-to-br from-yellow-300 via-amber-400 to-yellow-500 border-4 border-yellow-200 flex items-center justify-center text-white text-2xl font-black shadow-2xl transform -rotate-12">
                                ₹
                            </div>
                            <div className="w-16 h-16 rounded-full bg-gradient-to-br from-yellow-400 to-orange-500 border-4 border-yellow-200 flex items-center justify-center text-white text-2xl font-black shadow-2xl transform rotate-12 -ml-6 mt-2">
                                ₹
                            </div>
                        </div>

                    </div>
                </div>
            </div>
        </section>
    );
};

export default IncomeOpportunity;
