import React, { useState } from 'react';
import { ChevronRight } from 'lucide-react';

const opportunities = [
    {
        title: "Brokerage Sharing",
        description: "Earn a highly competitive percentage of the brokerage generated by your clients' trading activities."
    },
    {
        title: "Mutual Fund Distribution",
        description: "Build a stable trail income by distributing a wide variety of direct and regular mutual funds."
    },
    {
        title: "Insurance",
        description: "Cross-sell life and general insurance products to your clients and earn attractive commissions."
    },
    {
        title: "IPOs",
        description: "Facilitate IPO investments for your network and get rewarded for successful allotments."
    },
    {
        title: "Loans",
        description: "Refer clients for personal, business, or margin funding loans and earn lucrative referral fees."
    },
    {
        title: "Bonds & Corporate FDs",
        description: "Provide safe fixed-income investment options to clients and earn steady distribution payouts."
    },
    {
        title: "PMS & AIF Referrals",
        description: "Target High Net-worth Individuals for Portfolio Management Services and earn premium commissions."
    },
    {
        title: "Research Subscriptions",
        description: "Offer premium research and advisory subscriptions to your clients on a profit-sharing model."
    }
];

const IncomeOpportunity = () => {
    // We can use state if we want to change the right-side graphic on hover, 
    // but the screenshot implies a static beautiful illustration on the right.
    const [activeTab, setActiveTab] = useState(0);

    return (
        <section className="bg-white py-20 md:py-24">
            <div className="container mx-auto px-6">
                <div className="flex flex-col lg:flex-row gap-16 lg:gap-24 items-start">
                    
                    {/* Left Side: Content & Cards */}
                    <div className="w-full lg:w-7/12 flex flex-col">
                        
                        {/* Header */}
                        <div className="mb-10">
                            <h2 className="text-3xl md:text-5xl font-extrabold text-[#1e2c4c] mb-4 tracking-tight leading-tight uppercase">
                                MULTIPLE STREAMS OF INCOME
                            </h2>
                            <p className="text-gray-500 text-base md:text-lg leading-relaxed">
                                Partner with DB Fintrix and monetize your network across 8 different high-yielding financial products.
                            </p>
                        </div>

                        {/* Cards List - Native page scrolling */}
                        <div className="flex flex-col gap-4 pr-4">
                            {opportunities.map((item, index) => (
                                <div 
                                    key={index}
                                    onMouseEnter={() => setActiveTab(index)}
                                    className={`group flex items-center justify-between p-5 md:p-6 rounded-xl border transition-all cursor-pointer ${activeTab === index ? 'border-[#3b82f6] shadow-sm bg-blue-50/30' : 'border-gray-200 hover:border-gray-300 bg-white'}`}
                                >
                                    <div className="pr-4">
                                        <h3 className="text-[#1e2c4c] font-bold text-lg mb-1.5">
                                            {item.title}
                                        </h3>
                                        <p className="text-gray-500 text-sm leading-relaxed">
                                            {item.description}
                                        </p>
                                    </div>
                                    <div className={`shrink-0 transition-transform ${activeTab === index ? 'text-[#3b82f6] translate-x-1' : 'text-gray-300 group-hover:text-gray-400 group-hover:translate-x-1'}`}>
                                        <ChevronRight className="w-6 h-6" strokeWidth={2.5} />
                                    </div>
                                </div>
                            ))}
                        </div>
                    </div>

                    {/* Right Side: Custom CSS Illustration */}
                    <div className="w-full lg:w-5/12 relative hidden lg:flex items-center justify-center sticky top-32 h-[600px] transform scale-90 xl:scale-100 origin-right">
                        
                        {/* Decorative background circle */}
                        <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[450px] h-[450px] rounded-full bg-red-50/80 -z-10"></div>
                        
                        {/* Floating elements behind */}
                        <div className="absolute top-20 left-10 text-yellow-400 animate-pulse">
                            <svg width="24" height="24" viewBox="0 0 24 24" fill="currentColor"><path d="M12 2L15 9L22 12L15 15L12 22L9 15L2 12L9 9L12 2Z"/></svg>
                        </div>
                        <div className="absolute bottom-32 left-0 text-blue-400 animate-pulse delay-700">
                            <svg width="32" height="32" viewBox="0 0 24 24" fill="currentColor"><path d="M12 2L15 9L22 12L15 15L12 22L9 15L2 12L9 9L12 2Z"/></svg>
                        </div>

                        {/* Floating Icons Column */}
                        <div className="absolute left-10 top-1/2 -translate-y-1/2 flex flex-col gap-3 bg-red-400 rounded-full p-2 py-4 shadow-xl shadow-red-200 z-20">
                            <div className="w-10 h-10 bg-white rounded-xl shadow-sm flex items-center justify-center text-green-500 font-bold">"</div>
                            <div className="w-10 h-10 bg-white rounded-xl shadow-sm flex items-center justify-center text-blue-500">▶</div>
                            <div className="w-10 h-10 bg-white rounded-xl shadow-sm flex items-center justify-center text-yellow-500">∞</div>
                        </div>

                        {/* Main Browser Window */}
                        <div className="relative w-[500px] h-[350px] bg-white rounded-2xl shadow-[0_20px_50px_rgba(0,0,0,0.1)] border border-gray-100 flex flex-col z-10 overflow-hidden transform transition-transform hover:scale-105 duration-500">
                            
                            {/* Browser Top Bar */}
                            <div className="h-12 bg-[#5c6ac4] w-full flex items-center px-4 gap-2">
                                <div className="flex gap-1.5 mr-4">
                                    <div className="w-3 h-3 rounded-full bg-white/30"></div>
                                    <div className="w-3 h-3 rounded-full bg-white/30"></div>
                                    <div className="w-3 h-3 rounded-full bg-white/30"></div>
                                </div>
                                <div className="h-6 flex-grow bg-white/20 rounded-md max-w-[200px]"></div>
                            </div>

                            {/* Browser Body */}
                            <div className="p-6 bg-[#f8f9fe] flex-grow flex flex-col gap-6">
                                
                                <div className="flex gap-6">
                                    {/* Bar Chart Box */}
                                    <div className="bg-[#fef3c7] rounded-xl p-4 flex-grow h-32 relative shadow-sm border border-orange-100">
                                        <div className="absolute bottom-6 left-4 right-4 h-16 flex items-end justify-around gap-2">
                                            <div className="w-6 bg-orange-400 rounded-t-md" style={{ height: '40%' }}></div>
                                            <div className="w-6 bg-orange-400 rounded-t-md" style={{ height: '70%' }}></div>
                                            <div className="w-6 bg-orange-400 rounded-t-md" style={{ height: '90%' }}></div>
                                            <div className="w-6 bg-orange-400 rounded-t-md" style={{ height: '60%' }}></div>
                                        </div>
                                        {/* Slider underneath */}
                                        <div className="absolute bottom-4 left-4 right-4 h-2 bg-white rounded-full">
                                            <div className="w-1/2 h-full bg-orange-400 rounded-full relative">
                                                <div className="absolute right-0 top-1/2 -translate-y-1/2 w-3 h-3 bg-blue-500 rounded-full border-2 border-white"></div>
                                            </div>
                                        </div>
                                    </div>

                                    {/* Pie Charts Area */}
                                    <div className="flex flex-col gap-3">
                                        <div className="w-16 h-16 rounded-full bg-green-100 relative overflow-hidden border border-green-200">
                                            <div className="absolute top-0 right-0 w-1/2 h-full bg-green-500"></div>
                                            <div className="absolute bottom-0 right-0 w-full h-1/2 bg-green-500 transform rotate-45 origin-center"></div>
                                        </div>
                                        <div className="w-12 h-12 rounded-full bg-green-100 relative overflow-hidden border border-green-200 self-end">
                                            <div className="absolute top-0 right-0 w-1/2 h-full bg-green-500 opacity-50"></div>
                                        </div>
                                    </div>
                                </div>

                                {/* Text Placeholders */}
                                <div className="flex flex-col gap-3">
                                    <div className="w-full h-3 bg-gray-200 rounded-full"></div>
                                    <div className="w-3/4 h-3 bg-gray-200 rounded-full"></div>
                                    <div className="w-5/6 h-3 bg-gray-200 rounded-full"></div>
                                </div>

                            </div>
                        </div>

                        {/* Floating Coins */}
                        <div className="absolute -bottom-6 right-10 flex z-30 drop-shadow-lg">
                            <div className="w-16 h-16 rounded-full bg-gradient-to-br from-yellow-300 to-orange-400 border-4 border-yellow-200 flex items-center justify-center text-white text-2xl font-bold shadow-lg transform -rotate-12">
                                ₹
                            </div>
                            <div className="w-16 h-16 rounded-full bg-gradient-to-br from-yellow-300 to-orange-400 border-4 border-yellow-200 flex items-center justify-center text-white text-2xl font-bold shadow-lg transform rotate-12 -ml-6">
                                ₹
                            </div>
                        </div>

                    </div>
                </div>
            </div>
        </section>
    );
};

export default IncomeOpportunity;
